server:
  port: 8080

logging:
  level:
    com:
      example:
        monolithic: debug # project logging
    org:
      springframework:
        transaction: debug # spring transaction logging
        web: debug # spring web logging
        security: debug # spring security logging
        orm:
          jpa: debug # spring orm jpa logging
      hibernate:
        SQL: debug # hibernate sql logging
        type.descriptor.sql: trace # DDL 시 입력된 실제 Value 값을 확인할려면 trace 으로 사용


spring:
  h2:
    console:
      enabled: true # h2 console 사용
      path: /h2 # localhost:port/h2 로 접근 가능
      settings:
        trace: false # Print additional trace information
        web-allow-others: true  # 브라우저로 접근가능하게 하기
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        format_sql: true # sql query pretty option
        default_batch_fetch_size: 1000 # fetch join in query
  servlet:
    multipart:
      enabled: true # file upload true
      max-file-size: 1024MB # single file max size
      max-request-size: 1024MB # total file request max size
  messages:
    basename: classpath:/i18n/messages, classpath:/i18n/errors
  mvc:
    throw-exception-if-no-handler-found: true
