server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/monolithic?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul
    username: 'root'
    password: '1234'
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect # mysql DB engine
    properties:
      hibernate:
        format_sql: true # sql query pretty option
        default_batch_fetch_size: 1000 # fetch join in query
  messages:
    basename: classpath:/i18n/messages, classpath:/i18n/errors
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false